In [17]:
import pandas as pd 

#Se hace la conexión a la DB desde local al ser un archivo muy pesado para subirlo a GitHub. 

df1 = pd.read_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final/db/steam_games.csv")

C:\Users\esteb\AppData\Local\Temp\ipykernel_26716\4226614299.py:5: DtypeWarning: Columns (0: windows, 1: mac, 2: linux) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final/db/steam_games.csv")

In [44]:
print(f"Estado Inicial del DataFrame: {df1.shape[0]} filas, {df1.shape[1]} columnas. \n \n Columnas: {df1.columns} \n \n Tipos de Datos: \n {df1.dtypes} \n \n Valores Nulos: {df1.isnull().sum()}")

Estado Inicial del DataFrame: 139580 filas, 42 columnas.

 Columnas: Index(['app_id', 'name', 'release_date', 'price', 'price_status',
       'estimated_owners', 'developers', 'publishers', 'genres', 'categories',
       'tags', 'positive', 'negative', 'recommendations', 'peak_ccu',
       'metacritic_score', 'user_score', 'average_playtime_forever',
       'median_playtime_forever', 'average_playtime_2weeks',
       'median_playtime_2weeks', 'short_description', 'about_the_game',
       'detailed_description', 'notes', 'achievements', 'dlc_count',
       'packages', 'supported_languages', 'full_audio_languages', 'windows',
       'mac', 'linux', 'header_image', 'screenshots', 'movies', 'website',
       'support_url', 'support_email', 'metacritic_url',
       'steam_store_available', 'steam_spy_available'],
      dtype='str')

 Tipos de Datos:
 app_id                        int64
name                            str
release_date                    str
price                       float64
price_status                    str
estimated_owners                str
developers                      str
publishers                      str
genres                          str
categories                      str
tags                            str
positive                      int64
negative                      int64
recommendations             float64
peak_ccu                      int64
metacritic_score            float64
user_score                    int64
average_playtime_forever      int64
median_playtime_forever       int64
average_playtime_2weeks       int64
median_playtime_2weeks        int64
short_description               str
about_the_game                  str
detailed_description            str
notes                           str
achievements                float64
dlc_count                     int64
packages                        str
supported_languages             str
full_audio_languages            str
windows                      object
mac                          object
linux                        object
header_image                    str
screenshots                     str
movies                          str
website                         str
support_url                     str
support_email                   str
metacritic_url                  str
steam_store_available          bool
steam_spy_available            bool
dtype: object

 Valores Nulos: app_id                           0
name                            16
release_date                    83
price                         1172
price_status                     0
estimated_owners                 0
developers                       0
publishers                       0
genres                           0
categories                       0
tags                             0
positive                         0
negative                         0
recommendations              31612
peak_ccu                         0
metacritic_score             38544
user_score                       0
average_playtime_forever         0
median_playtime_forever          0
average_playtime_2weeks          0
median_playtime_2weeks           0
short_description             8330
about_the_game                8440
detailed_description          8419
notes                       113453
achievements                 16774
dlc_count                        0
packages                         0
supported_languages             19
full_audio_languages         30747
windows                         15
mac                             15
linux                           15
header_image                    97
screenshots                      0
movies                           0
website                      85229
support_url                  79389
support_email                24129
metacritic_url              135291
steam_store_available            0
steam_spy_available              0
dtype: int64

In [45]:
df1.head()

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,...,linux,header_image,screenshots,movies,website,support_url,support_email,metacritic_url,steam_store_available,steam_spy_available
0,876310,BIG POGO MAN,2018-06-25,4.99,paid,0 - 20000,"[""WooJuDev""]","[""WooJuDev""]","[""Adventure"", ""Casual"", ""Indie"", ""Sports""]","[""Single-player"", ""Steam Achievements"", ""Steam...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,NaN,woojudev@gmail.com,NaN,True,True
1,876320,Hyperspace Delivery Service,2019-06-05,9.99,paid,0 - 20000,"[""Zotnip""]","[""Zotnip""]","[""Action"", ""Adventure"", ""Indie"", ""Simulation"",...","[""Single-player"", ""Steam Achievements"", ""Full ...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],http://hyperspacedeliveryservice.com,http://hyperspacedeliveryservice.com,info@zotnip.com,NaN,True,True
2,876340,VR Slots 3D,2018-08-30,0.00,free,0 - 20000,"[""Belka VR""]","[""Belka VR""]","[""Casual"", ""Free To Play"", ""Indie"", ""Early Acc...","[""Single-player"", ""Tracked Controller Support""...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,NaN,support@belkavr.com,NaN,True,True
3,876380,Underwater hunting,2018-06-20,0.99,paid,0 - 20000,"[""GiBar""]","[""RoBot""]","[""Adventure"", ""Indie"", ""RPG""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...",...,False,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,NaN,robot72@yandex.ru,NaN,True,True
4,876410,Greenspawn Restaurant,2018-07-20,3.99,paid,0 - 20000,"[""Apple Dash""]","[""Apple Dash""]","[""Action"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Famil...",...,True,https://shared.akamai.steamstatic.com/store_it...,"[""https://shared.akamai.steamstatic.com/store_...",[],NaN,NaN,fshpsmgc@gmail.com,NaN,True,True

In [46]:
#Prueba de la columna recommendations

df_recom = df1.recommendations[df1.recommendations > 0]
df_recom.count()

np.int64(22173)

In [47]:
#Prueba de los valores en Tag. ¿Son importantes para el análisis?
df1.tags[1]

'["Indie", "Simulation", "Adventure", "Action", "Strategy", "Space", "Pixel Graphics", "Retro", "Sci-fi", "2D", "Singleplayer", "Great Soundtrack", "FPS", "Choose Your Own Adventure", "Perma Death", "Survival", "Inventory Management", "Resource Management", "Replay Value", "Space Sim"]'

In [48]:
#Se descartan las columnas que no aportan informacion relevante para el análisis en una copia del DB. 

df1_clean = df1.copy()

df1_clean.drop(columns=['metacritic_score', 'user_score','average_playtime_2weeks','median_playtime_2weeks', 'about_the_game','detailed_description', 'notes', 'achievements','packages', 'supported_languages', 'full_audio_languages', 'windows','mac','linux', 'header_image', 'screenshots', 'movies', 'website','support_url', 'support_email', 'metacritic_url','steam_store_available', 'steam_spy_available'], inplace=True)

In [49]:
df1_clean.head()

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,tags,positive,negative,recommendations,peak_ccu,average_playtime_forever,median_playtime_forever,short_description,dlc_count
0,876310,BIG POGO MAN,2018-06-25,4.99,paid,0 - 20000,"[""WooJuDev""]","[""WooJuDev""]","[""Adventure"", ""Casual"", ""Indie"", ""Sports""]","[""Single-player"", ""Steam Achievements"", ""Steam...","[""Sports"", ""Adventure"", ""Indie"", ""Casual""]",48,12,0.0,0,0,0,"Climb mountain made of odds and ends, riding P...",0
1,876320,Hyperspace Delivery Service,2019-06-05,9.99,paid,0 - 20000,"[""Zotnip""]","[""Zotnip""]","[""Action"", ""Adventure"", ""Indie"", ""Simulation"",...","[""Single-player"", ""Steam Achievements"", ""Full ...","[""Indie"", ""Simulation"", ""Adventure"", ""Action"",...",42,4,0.0,0,0,0,You’ve been hired to make a delivery to planet...,1
2,876340,VR Slots 3D,2018-08-30,0.00,free,0 - 20000,"[""Belka VR""]","[""Belka VR""]","[""Casual"", ""Free To Play"", ""Indie"", ""Early Acc...","[""Single-player"", ""Tracked Controller Support""...","[""Casual"", ""Free to Play"", ""Early Access"", ""In...",17,18,0.0,0,0,0,Try for free the first VR Slots in the world. ...,0
3,876380,Underwater hunting,2018-06-20,0.99,paid,0 - 20000,"[""GiBar""]","[""RoBot""]","[""Adventure"", ""Indie"", ""RPG""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Adventure"", ""Indie"", ""RPG"", ""Female Protagon...",40,33,0.0,0,0,0,Underwater hunting: Plunge into the underwater...,2
4,876410,Greenspawn Restaurant,2018-07-20,3.99,paid,0 - 20000,"[""Apple Dash""]","[""Apple Dash""]","[""Action"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Famil...","[""Action"", ""Indie""]",1,1,0.0,0,0,0,Greenspawn Restaurant is a unique combination ...,0

In [50]:
df1_clean.isnull().sum()

app_id                          0
name                           16
release_date                   83
price                        1172
price_status                    0
estimated_owners                0
developers                      0
publishers                      0
genres                          0
categories                      0
tags                            0
positive                        0
negative                        0
recommendations             31612
peak_ccu                        0
average_playtime_forever        0
median_playtime_forever         0
short_description            8330
dlc_count                       0
dtype: int64

In [51]:
#Al ver que recommendations tiene +30000 nulos y solo 22000 valores superiores a 0, se decide dropearla. El parametro para medir si el juego tiene buena valoración puede medirse por criticas positivas y negativas.

df1_clean.drop(columns="recommendations", inplace=True)

In [52]:
df1_clean[df1_clean["peak_ccu"] == 0].count()

#AL ver que el peak_ccu, que en una primer instancia se marcó como util al medir el pico máximo de jugadores en linea, finalmente no aporta información relevante al tener alrededor de 120.000 registros en 0, se descarta.

df1_clean.drop(columns="peak_ccu", inplace=True)

In [53]:
df1_clean[df1_clean["estimated_owners"]=="0 - 20000"]

,app_id,name,release_date,price,price_status,estimated_owners,developers,publishers,genres,categories,tags,positive,negative,average_playtime_forever,median_playtime_forever,short_description,dlc_count
0,876310,BIG POGO MAN,2018-06-25,4.99,paid,0 - 20000,"[""WooJuDev""]","[""WooJuDev""]","[""Adventure"", ""Casual"", ""Indie"", ""Sports""]","[""Single-player"", ""Steam Achievements"", ""Steam...","[""Sports"", ""Adventure"", ""Indie"", ""Casual""]",48,12,0,0,"Climb mountain made of odds and ends, riding P...",0
1,876320,Hyperspace Delivery Service,2019-06-05,9.99,paid,0 - 20000,"[""Zotnip""]","[""Zotnip""]","[""Action"", ""Adventure"", ""Indie"", ""Simulation"",...","[""Single-player"", ""Steam Achievements"", ""Full ...","[""Indie"", ""Simulation"", ""Adventure"", ""Action"",...",42,4,0,0,You’ve been hired to make a delivery to planet...,1
2,876340,VR Slots 3D,2018-08-30,0.00,free,0 - 20000,"[""Belka VR""]","[""Belka VR""]","[""Casual"", ""Free To Play"", ""Indie"", ""Early Acc...","[""Single-player"", ""Tracked Controller Support""...","[""Casual"", ""Free to Play"", ""Early Access"", ""In...",17,18,0,0,Try for free the first VR Slots in the world. ...,0
3,876380,Underwater hunting,2018-06-20,0.99,paid,0 - 20000,"[""GiBar""]","[""RoBot""]","[""Adventure"", ""Indie"", ""RPG""]","[""Single-player"", ""Multi-player"", ""Co-op"", ""On...","[""Adventure"", ""Indie"", ""RPG"", ""Female Protagon...",40,33,0,0,Underwater hunting: Plunge into the underwater...,2
4,876410,Greenspawn Restaurant,2018-07-20,3.99,paid,0 - 20000,"[""Apple Dash""]","[""Apple Dash""]","[""Action"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Famil...","[""Action"", ""Indie""]",1,1,0,0,Greenspawn Restaurant is a unique combination ...,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139241,4182200,Saylor Anime Puzzle,2025-12-06,1.99,paid,0 - 20000,"[""Saylor Games""]","[""Saylor Games""]","[""Adventure"", ""Casual"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Famil...",[],0,0,0,0,Saylor Anime puzzle is simplictic jigsaw puzzl...,0
139251,4186750,HOT ASSES,2025-12-05,3.99,paid,0 - 20000,"[""Hell Bomb Studio""]","[""Hell Bomb Studio""]","[""Action"", ""Adventure"", ""Casual"", ""Indie"", ""RP...","[""Single-player"", ""Steam Achievements"", ""Famil...",[],0,0,0,0,HOT ASSES - is an erotic game in the genre of ...,0
139261,4193800,Hentai Clicker: Stella is streaming,2025-12-11,2.99,paid,0 - 20000,"[""Sexy Baguette Studio""]","[""Sexy Baguette Studio""]","[""Casual"", ""Indie""]","[""Single-player"", ""Steam Achievements"", ""Famil...",[],0,0,0,0,🎤 Step into the spotlight with Hentai Clicker:...,0
139268,4200330,Sex Game - BDSM - Episode 4,2025-12-06,4.99,paid,0 - 20000,"[""EroticGamesClub""]","[""EroticGamesClub""]","[""Adventure"", ""Casual"", ""Simulation""]","[""Single-player"", ""Steam Achievements"", ""Steam...",[],0,0,0,0,Immerse yourself in an erotic visual novel tha...,0
139270,4203010,Santa’s Little Secrets – Naughty Jigsaw,2025-12-10,1.99,paid,0 - 20000,"[""Black Hole""]","[""Black Hole""]","[""Casual""]","[""Single-player"", ""Steam Achievements"", ""Custo...",[],0,0,0,0,Christmas just got a lot hotter! 🔥💋 Santa’s Li...,0

In [54]:
df1_clean.columns

#Chequeadas las columnas que son relevantes para el análisis, procedemos al manejo de nulos y el recorte de la DB que resulta muy pesada para ser trabajada en un Repositorio de GItHub.

Index(['app_id', 'name', 'release_date', 'price', 'price_status',
       'estimated_owners', 'developers', 'publishers', 'genres', 'categories',
       'tags', 'positive', 'negative', 'average_playtime_forever',
       'median_playtime_forever', 'short_description', 'dlc_count'],
      dtype='str')

In [55]:
df1_clean["short_description"] =df1_clean["short_description"].fillna("NO INFO")

In [56]:
df1_clean.short_description[df1_clean.short_description == "NO INFO"].count()

#El numero de "NO INFO" coincide con el numero previo de nulos.

np.int64(8330)

In [57]:
df1_clean.isnull().sum()

app_id                         0
name                          16
release_date                  83
price                       1172
price_status                   0
estimated_owners               0
developers                     0
publishers                     0
genres                         0
categories                     0
tags                           0
positive                       0
negative                       0
average_playtime_forever       0
median_playtime_forever        0
short_description              0
dlc_count                      0
dtype: int64

In [58]:
#La cantidad de nulos restantes en el DB representa un 0,01% del total de registros(1300 nulos / +130000 registros totales), por lo que se decide dropearlos sin representar una perdida significativa de información.

df1_clean.dropna(inplace=True)

df1_clean.isnull().sum()

app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
dtype: int64

In [59]:
#Verificado que los vlaores de los registros de la DB son válidos, se procede a hacer el recorte de los registros para tener un volumen de información menos pesado y más manipulable para realizar el análisis.
#Se toman como criterios de recorte los factores determinantes para el éxito de un videojuego. EN este sentido, recortaremos los registros con menor cantidad de ventas (expresadaas en la columna estimated_owners).

df1_clean.estimated_owners.value_counts()

estimated_owners
0 - 20000                     62562
0 .. 20,000                   29449
0 - 0                         21185
20000 - 50000                  7305
20,000 .. 50,000               3953
50000 - 100000                 2994
50,000 .. 100,000              2296
100,000 .. 200,000             1731
100000 - 200000                1671
200,000 .. 500,000             1670
200000 - 500000                1131
500,000 .. 1,000,000            719
1,000,000 .. 2,000,000          480
500000 - 1000000                405
2,000,000 .. 5,000,000          294
1000000 - 2000000               224
2000000 - 5000000                99
5,000,000 .. 10,000,000          89
10,000,000 .. 20,000,000         35
5000000 - 10000000               30
20,000,000 .. 50,000,000         18
10000000 - 20000000              14
20000000 - 50000000              11
50000000 - 100000000              4
100,000,000 .. 200,000,000        3
50,000,000 .. 100,000,000         3
100000000 - 200000000             1
Name: count, dtype: int64

In [60]:
#Al verificar los valores por cada rango de ventas, vemos que los valores tienen diferencia de sintaxis, por lo que se debe reemplazar las "," y los ".." que hacen que los registros con la misma cantidad de ventas se vean representados en distintos grupos.

df1_clean["estimated_owners"] = df1_clean.estimated_owners.str.replace(",", "").str.replace("..", "-")

In [61]:
df1_clean.estimated_owners.value_counts()

estimated_owners
0 - 20000                92011
0 - 0                    21185
20000 - 50000            11258
50000 - 100000            5290
100000 - 200000           3402
200000 - 500000           2801
500000 - 1000000          1124
1000000 - 2000000          704
2000000 - 5000000          393
5000000 - 10000000         119
10000000 - 20000000         49
20000000 - 50000000         29
50000000 - 100000000         7
100000000 - 200000000        4
Name: count, dtype: int64

In [62]:
#Normalizados los valores de estimated_owners, ahora si procedemos a recortar los registros que estén por debajo de los 20000 ventas.

df1_clean = df1_clean.drop(df1_clean[df1_clean.estimated_owners == "0 - 20000"].index)
df1_clean = df1_clean.drop(df1_clean[df1_clean.estimated_owners == "0 - 0"].index)

In [63]:
df1_clean.estimated_owners.value_counts()

estimated_owners
20000 - 50000            11258
50000 - 100000            5290
100000 - 200000           3402
200000 - 500000           2801
500000 - 1000000          1124
1000000 - 2000000          704
2000000 - 5000000          393
5000000 - 10000000         119
10000000 - 20000000         49
20000000 - 50000000         29
50000000 - 100000000         7
100000000 - 200000000        4
Name: count, dtype: int64

In [64]:
df1_clean.count()

app_id                      25180
name                        25180
release_date                25180
price                       25180
price_status                25180
estimated_owners            25180
developers                  25180
publishers                  25180
genres                      25180
categories                  25180
tags                        25180
positive                    25180
negative                    25180
average_playtime_forever    25180
median_playtime_forever     25180
short_description           25180
dlc_count                   25180
dtype: int64

In [65]:
#Ya con el recorte de los registros y el tratamiento de los nulos, pasamos de un DB de +130.000 registros a uno de 25.000 obteniendo un volumen de datos más manipulable y menos pesado para el análisis. Además del recorte de los registros (files), también recortamos información de poca utilidad para el análisis en forma de columnas, reduciendo el tamaño del DB en sus dos axis.

print(f"Estado Intermedio del DataFrame: {df1_clean.shape[0]} filas, {df1_clean.shape[1]} columnas. \n \n Columnas: {df1_clean.columns} \n \n Tipos de Datos: \n {df1_clean.dtypes} \n \n Valores Nulos: {df1_clean.isnull().sum()}")

Estado Intermedio del DataFrame: 25180 filas, 17 columnas.

 Columnas: Index(['app_id', 'name', 'release_date', 'price', 'price_status',
       'estimated_owners', 'developers', 'publishers', 'genres', 'categories',
       'tags', 'positive', 'negative', 'average_playtime_forever',
       'median_playtime_forever', 'short_description', 'dlc_count'],
      dtype='str')

 Tipos de Datos:
 app_id                        int64
name                            str
release_date                    str
price                       float64
price_status                    str
estimated_owners                str
developers                      str
publishers                      str
genres                          str
categories                      str
tags                            str
positive                      int64
negative                      int64
average_playtime_forever      int64
median_playtime_forever       int64
short_description               str
dlc_count                     int64
dtype: object

 Valores Nulos: app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
dtype: int64

In [ ]:
#Con el DB ya recortado y limpio, se procede a exportarlo a un archivo CSV para poder ser utilizado en el análisis de datos. Se continuará con la limpieza de duplicados y la normalización de los datos que sean necesarios para el volumen de los datos de la DB limpia ya exportada.

#Nuevo indice de los registros + exportación:

df1_clean["new_app_id"] = range(1, len(df1_clean) + 1)
df1_clean.to_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final/db/steam_games_clean.csv", index=False)

In [ ]:
#Conexión a la nueva DB limpia para continuar con el tratamiento de duplicados y normalización de los datos.

df_clean = pd.read_csv("C:/Users/esteb/Documents/Esteban/CURSOS/Data-analisis-ComIT_ok/proyecto-final-data-analysis/data/steam_games_clean.csv")

In [ ]:
# Normalización de formato de fechas a partir de la columna release_date

patron_fecha = r"^\d{4}-\d{2}-\d{2}$"

formato_correcto = df_clean["release_date"].astype(str).str.match(patron_fecha)

fechas_convertidas = pd.to_datetime(
    df_clean["release_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

fecha_valida = fechas_convertidas.notna()

fechas_invalidas = df_clean[~(formato_correcto & fecha_valida)]

fechas_invalidas["release_date"].count()

#No se encuentran errores en el formato de las fechas.

np.int64(0)

In [16]:
#Con los valores de las fechas validados, verificamos que las fechas de lanzamiento sean congruentes con el lanzamiento de Steam. Evitando que haya algún juego con fecha de lanzamiento muy antigua.

df_clean.release_date[df_clean.release_date < "1995-01-01"]

#No se encuentran fechas fuera de lugar.

Series([], Name: release_date, dtype: str)

In [ ]:
#Control de valores negativos en la columna de precios. No hay valores negativos.

df_clean.price[df_clean.price < 0].count()

np.int64(0)

In [42]:
#Verificación de duplicados en la DB. Normaización de nombres y detección de duplicados a partir de fecha y nombre. 28 duplicados detectados.

df_clean["name"] = df_clean.name.str.lower()

duplicados = df_clean[df_clean.duplicated(subset=["name", "release_date"], keep=False)]

duplicados.count()

app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
new_app_id                  0
dtype: int64

In [41]:
#Eliminación de duplicados.

df_clean.drop_duplicates(subset=["name", "release_date"], keep="first", inplace=True)

#Verificación de duplicados tras la eliminación de los mismos.

duplicados.count()

app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
new_app_id                  0
dtype: int64

In [66]:
print(f"Estado Final del DataFrame: {df_clean.shape[0]} filas, {df_clean.shape[1]} columnas. \n \n Columnas: {df_clean.columns} \n \n Tipos de Datos: \n {df_clean.dtypes} \n \n Valores Nulos: {df_clean.isnull().sum()} \n \n Duplicados: {duplicados.count()}")

Estado Final del DataFrame: 25152 filas, 18 columnas.

 Columnas: Index(['app_id', 'name', 'release_date', 'price', 'price_status',
       'estimated_owners', 'developers', 'publishers', 'genres', 'categories',
       'tags', 'positive', 'negative', 'average_playtime_forever',
       'median_playtime_forever', 'short_description', 'dlc_count',
       'new_app_id'],
      dtype='str')

 Tipos de Datos:
 app_id                        int64
name                            str
release_date                    str
price                       float64
price_status                    str
estimated_owners                str
developers                      str
publishers                      str
genres                          str
categories                      str
tags                            str
positive                      int64
negative                      int64
average_playtime_forever      int64
median_playtime_forever       int64
short_description               str
dlc_count                     int64
new_app_id                    int64
dtype: object

 Valores Nulos: app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
new_app_id                  0
dtype: int64

 Duplicados: app_id                      0
name                        0
release_date                0
price                       0
price_status                0
estimated_owners            0
developers                  0
publishers                  0
genres                      0
categories                  0
tags                        0
positive                    0
negative                    0
average_playtime_forever    0
median_playtime_forever     0
short_description           0
dlc_count                   0
new_app_id                  0
dtype: int64